# Generated by Django 4.2.7 on 2024-06-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayrollManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='basic_days_after_holidays',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salary',
            name='worked_day_off_days',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salary',
            name='worked_days',
            field=models.FloatField(),
        ),
    ]
