# Generated by Django 4.2.7 on 2024-06-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayrollManager', '0002_alter_salary_basic_days_after_holidays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='actual_work_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='average_hours_per_day',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='basic_days_after_holidays',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='basic_hours_after_holidays',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='holiday_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='overtime_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='penalty_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='sunday_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='total_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='worked_day_off_days',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='worked_day_off_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='worked_days',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='worked_holiday_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
